suppressPackageStartupMessages({library(survey);library(jsonlite)})
options(survey.lonely.psu='fail');o<-'analysis/tasks/V3-I01/rev-1/work';q<-'analysis/tasks/V3-Q01/rev-1/work';a<-readRDS(file.path(o,'prepared.rds'));b<-a$base;d<-svydesign(id=~SDMVPSU,strata=~SDMVSTRA,weights=~weight_mec_18yr,nest=TRUE,data=b[is.finite(b$weight_mec_18yr)&b$weight_mec_18yr>0,]);d<-subset(d,reference)
near<-function(x,y)stopifnot(isTRUE(all.equal(as.numeric(x),as.numeric(y),tolerance=1e-8,check.attributes=FALSE)))
tests<-rbind(read.csv(file.path(o,'table1_tests.csv')),read.csv(file.path(o,'S2_S5_tests.csv')));stopifnot(nrow(tests)==90,sum(is.finite(tests$p))==85,all(tests$reason[!is.finite(tests$p)]=='structurally coupled; descriptive only'))
for(t in unique(tests$table)){r<-tests[tests$table==t,];near(r$p_holm,p.adjust(r$p,'holm',n=18));near(r$p_BH,p.adjust(r$p,'BH',n=18));stopifnot(all(r$n+r$missing_n==nrow(d$variables)))}
for(g in c('frail','quart_NLR')){t<-if(g=='frail')'Table1'else'S2';d$variables$group<-d$variables[[g]];for(v in c('age','sex')){d$variables$value<-d$variables[[v]];r<-if(v=='age')svyranktest(value~group,d,test='wilcoxon')else svychisq(~value+group,d,statistic='F');near(tests$p[tests$table==t&tests$variable==v],r$p.value)}}
desc<-rbind(read.csv(file.path(o,'table1_descriptions.csv')),read.csv(file.path(o,'S2_S5_descriptions.csv')));stopifnot(all(desc$total==desc$observed+desc$missing));catrows<-desc[is.finite(desc$percent),];for(key in unique(paste(catrows$table,catrows$group,catrows$variable))){r<-catrows[paste(catrows$table,catrows$group,catrows$variable)==key,];near(sum(r$n),unique(r$observed));near(sum(r$percent),100);near(sum(r$weighted_percent),100)}
r<-subset(desc,table=='Table1'&group=='All'&variable=='age');near(c(r$q25,r$median,r$q75),quantile(d$variables$age,c(.25,.5,.75)));near(c(r$weighted_q25,r$weighted_median,r$weighted_q75),coef(svyquantile(~age,d,c(.25,.5,.75),ci=FALSE)))
write_json(list(status='PASS',planned_test_rows=90,actual_tests=85,structurally_coupled_descriptive_only=5,independently_refitted_tests=c('Table1 age','Table1 sex','S2 age','S2 sex'),denominators_and_category_sums='all_rows_pass',age_quantiles='unweighted_and_survey_recomputed',family_adjustments='all_five_families_n18_pass'),file.path(q,'table_numeric_checks.json'),pretty=TRUE,auto_unbox=TRUE);cat('TABLE QA PASS\n')
