suppressPackageStartupMessages({library(survey);library(splines);library(jsonlite)})
out<-'analysis/tasks/V3-I01/rev-1/work'; options(survey.lonely.psu='fail',contrasts=c('contr.treatment','contr.poly'));a<-readRDS(file.path(out,'prepared.rds'));list2env(a,.GlobalEnv)
stopifnot(isTRUE(fromJSON('analysis/tasks/V3-Q01/rev-1/work/plan_review_v2.json')$execution_approved))
writeout<-function(x,n)write.csv(x,file.path(out,paste0(n,'.csv')),row.names=FALSE)
full<-svydesign(ids=~SDMVPSU,strata=~SDMVSTRA,weights=~weight_mec_18yr,nest=TRUE,data=base[is.finite(base$weight_mec_18yr)&base$weight_mec_18yr>0,]);diet<-svydesign(ids=~SDMVPSU,strata=~SDMVSTRA,weights=~weight_diet14,nest=TRUE,data=base[is.finite(base$weight_diet14)&base$weight_diet14>0,])
res<-list(continuous=list(),quartile=list(),trend=list(),omnibus=list(),spline=list(),curves=list(),interactions=list(),slopes=list(),audit=list());bases<-list();rows<-list()
add<-function(type,x)res[[type]][[length(res[[type]])+1]]<<-x
fit<-function(d,terms,label,marker,response='frail') {
  omit<-terms[vapply(terms,function(v)v%in%names(d$variables)&&is.factor(d$variables[[v]])&&length(unique(d$variables[[v]]))==1,logical(1))];terms<-setdiff(terms,omit);df<-degf(d);n<-nrow(d$variables);ev<-sum(d$variables[[response]]>0);formula<-reformulate(terms,response)
  result<-tryCatch({stopifnot(n>0,df>0);if(response=='frail')stopifnot(ev>0,ev<n);M<-model.matrix(formula,d$variables);stopifnot(qr(M,tol=1e-10)$rank==ncol(M));f<-svyglm(formula,d,family=quasibinomial(),control=glm.control(maxit=100));stopifnot(f$converged,f$df.residual>0,all(is.finite(coef(f))),all(is.finite(vcov(f))));f},error=function(e)e)
  ok<-!inherits(result,'error');add('audit',data.frame(model=label,marker=marker,n=n,events=ev,non_events=n-ev,df=df,status=if(ok)'estimable'else'non-estimable',reason=if(ok)''else conditionMessage(result),constant_factors_omitted=paste(omit,collapse='|'),weight_sum=sum(weights(d))))
  rows[[paste(label,marker,sep='_')]]<<-d$variables$SEQN
  if(ok)result else NULL
}
est<-function(f,d,term,label,m,contrast=term) {df<-degf(d);if(is.null(f)||!term%in%names(coef(f)))return(data.frame(model=label,marker=m,contrast=contrast,n=nrow(d$variables),beta=NA,se=NA,OR=NA,low=NA,high=NA,OR_doubling=NA,p=NA,df=df,status='non-estimable'))
 b<-unname(coef(f)[term]);s<-sqrt(vcov(f)[term,term]);data.frame(model=label,marker=m,contrast=contrast,n=nrow(d$variables),beta=b,se=s,OR=exp(b),low=exp(b-qt(.975,df)*s),high=exp(b+qt(.975,df)*s),OR_doubling=if(term=='x')exp(b*log(2))else NA,p=2*pt(-abs(b/s),df),df=df,status='estimable')}
wald<-function(f,terms,df){if(is.null(f))return(c(F=NA,p=NA));tryCatch({b<-coef(f)[terms];V<-vcov(f)[terms,terms,drop=FALSE];stopifnot(all(is.finite(b)));chol(V);F<-drop(t(b)%*%solve(V,b))/length(b);c(F=F,p=pf(F,length(b),df,lower.tail=FALSE))},error=function(e)c(F=NA,p=NA))}
basis<-function(x){k<-unname(quantile(x,c(1/3,2/3),type=7));bd<-range(x);stopifnot(length(unique(c(bd,k)))==4);B<-ns(x,knots=k,Boundary.knots=bd);L<-cbind(1,x);A<-qr.coef(qr(L,tol=1e-10),B);R<-B-L%*%A;q<-qr(R,tol=1e-10);stopifnot(q$rank==2);sel<-q$pivot[1:2];s<-sqrt(colSums(R[,sel,drop=FALSE]^2));Z<-sweep(R[,sel,drop=FALSE],2,s,'/');stopifnot(norm(qr.resid(qr(cbind(L,Z)),cbind(1,B)),'F')/norm(cbind(1,B),'F')<1e-10);list(Z=Z,knots=k,boundary=bd,A=A,selected=sel,scale=s)}
evalbasis<-function(x,b)sweep((ns(x,knots=b$knots,Boundary.knots=b$boundary)-cbind(1,x)%*%b$A)[,b$selected,drop=FALSE],2,b$scale,'/')
bs<-basis(seq(-2,3,length.out=301));stopifnot(max(abs(bs$Z-evalbasis(seq(-2,3,length.out=301),bs)))<1e-12)
splinefit<-function(d,terms,label,m){z<-tryCatch({bs<-basis(d$variables$x);d$variables$nl1<-bs$Z[,1];d$variables$nl2<-bs$Z[,2];f<-fit(d,c('x','nl1','nl2',terms),paste0(label,'_spline'),m);stopifnot(!is.null(f));w<-wald(f,c('nl1','nl2'),degf(d));wa<-wald(f,c('x','nl1','nl2'),degf(d));ref<-median(d$variables[[m]]);lim<-quantile(d$variables[[m]],c(.05,.95));grid<-sort(unique(c(exp(seq(log(lim[1]),log(lim[2]),length.out=121)),ref)));gz<-evalbasis(log(grid),bs);rz<-evalbasis(log(ref),bs);new<-d$variables[rep(1,length(grid)),];new$x<-log(grid);new$nl1<-gz[,1];new$nl2<-gz[,2];rn<-new;rn$x<-log(ref);rn$nl1<-rz[1,1];rn$nl2<-rz[1,2];tt<-delete.response(terms(f));D<-model.matrix(tt,new,contrasts.arg=f$contrasts)-model.matrix(tt,rn,contrasts.arg=f$contrasts);D<-D[,names(coef(f)),drop=FALSE];b<-drop(D%*%coef(f));se<-sqrt(pmax(0,rowSums((D%*%vcov(f))*D)));stopifnot(all(D[grid==ref,]==0));add('curves',data.frame(model=label,marker=m,value=grid,reference=ref,OR=exp(b),low=exp(b-qt(.975,degf(d))*se),high=exp(b+qt(.975,degf(d))*se)));bs$Z<-NULL;bases[[paste(label,m)]]<<-bs;data.frame(model=label,marker=m,F=w['F'],p=w['p'],overall_F=wa['F'],overall_p=wa['p'],df=degf(d),status='estimable',reason='')},error=function(e)data.frame(model=label,marker=m,F=NA,p=NA,overall_F=NA,overall_p=NA,df=degf(d),status='non-estimable',reason=conditionMessage(e)));add('spline',z)}
run<-function(d,terms,label,variants=TRUE,curves=FALSE,response='frail')for(m in markers){dd<-d;dd$variables$x<-log(dd$variables[[m]]);f<-fit(dd,c('x',terms),label,m,response);add('continuous',est(f,dd,'x',label,m));if(variants){dd$variables$q<-dd$variables[[paste0('quart_',m)]];dd$variables$score<-dd$variables[[paste0('trend_',m)]];fq<-fit(dd,c('q',terms),paste0(label,'_quartile'),m,response);for(j in 2:4)add('quartile',est(fq,dd,paste0('qQ',j),label,m,paste0('Q',j,'/Q1')));ww<-wald(fq,paste0('qQ',2:4),degf(dd));add('omnibus',data.frame(model=label,marker=m,F=ww['F'],p=ww['p'],df=degf(dd)));ft<-fit(dd,c('score',terms),paste0(label,'_trend'),m,response);add('trend',est(ft,dd,'score',label,m))};if(curves)splinefit(dd,terms,label,m)}
ref<-subset(full,reference);main<-subset(full,model2_domain);supp<-subset(full,supp_domain)
run(ref,m1,'M1_large');run(main,character(),'Unadjusted_matched');run(main,m1,'M1_matched');run(main,m2,'M2',curves=TRUE);run(supp,m2,'M2_supp_matched');run(supp,c(m2,extra),'M2_plus16',curves=TRUE)
strict<-subset(full,reference&!is.na(FI_candidate36));run(strict,m1,'Strict36_M1',FALSE)
partial<-subset(full,is.finite(FI30)&complete.cases(age,sex,race,cycle_adjust,NLR,MLR,SIRI,SII)&NLR>0&MLR>0&SIRI>0&SII>0);partial$variables$frail<-as.integer(partial$variables$FI30>.3);run(partial,m1,'FI30_M1',FALSE)
dd<-subset(diet,diet_domain);run(dd,m2,'Diet_day1_matched',FALSE);dd$variables$energy<-dd$variables$energy2;run(dd,m2,'Diet_mean2_matched',FALSE)
for(m in markers)for(mod in c('age_group','sex','bmi','activity','smoking','alcohol')){d<-main;d$variables$x<-log(d$variables[[m]]);d$variables$moderator<-d$variables[[mod]];terms<-c(setdiff(m2,mod),'x*moderator');f<-fit(d,terms,paste0('Interaction_',mod),m);it<-if(is.null(f))character()else grep('x:moderator|moderator.*:x',names(coef(f)),value=TRUE);w<-if(length(it))wald(f,it,degf(d))else c(F=NA,p=NA);add('interactions',data.frame(marker=m,moderator=mod,F=w['F'],p=w['p'],df_num=length(it),df=degf(d),n=nrow(d$variables),status=if(is.finite(w['p']))'estimable'else'non-estimable'))
for(lev in levels(d$variables$moderator)){take<-d$variables$moderator==lev;n<-sum(take);ev<-sum(d$variables$frail[take]);bb<-ss<-NA_real_;if(!is.null(f)&&n>0&&ev>0&&ev<n){new<-d$variables[1,,drop=FALSE];new$moderator<-factor(lev,levels=levels(d$variables$moderator));new$x<-1;nn<-new;nn$x<-0;tt<-delete.response(terms(f));D<-model.matrix(tt,new,contrasts.arg=f$contrasts)-model.matrix(tt,nn,contrasts.arg=f$contrasts);D<-D[,names(coef(f)),drop=FALSE];bb<-drop(D%*%coef(f));ss<-sqrt(drop(D%*%vcov(f)%*%t(D)))};add('slopes',data.frame(marker=m,moderator=mod,level=lev,n=n,events=ev,non_events=n-ev,pooled_n=nrow(d$variables),OR=exp(bb),low=exp(bb-qt(.975,degf(d))*ss),high=exp(bb+qt(.975,degf(d))*ss),status=if(is.finite(bb))'estimable'else'non-estimable'))}}
for(n in c('continuous','quartile','trend','omnibus','spline','interactions')){z<-do.call(rbind,res[[n]]);z$p_holm<-z$p_BH<-NA_real_;fam<-if(n=='interactions')rep('interaction',nrow(z))else z$model;planned<-switch(n,quartile=12,interactions=24,4);for(g in unique(fam)){i<-fam==g;z$p_holm[i]<-p.adjust(z$p[i],'holm',n=planned);z$p_BH[i]<-p.adjust(z$p[i],'BH',n=planned)};if(n=='spline'){z$overall_p_holm<-ave(z$overall_p,z$model,FUN=function(x)p.adjust(x,'holm',n=4));z$overall_p_BH<-ave(z$overall_p,z$model,FUN=function(x)p.adjust(x,'BH',n=4))};writeout(z,switch(n,continuous='continuous_models',quartile='quartile_models',trend='trend_models',omnibus='omnibus_tests',spline='spline_tests',interactions='interactions'))}
writeout(do.call(rbind,res$slopes),'subgroup_slopes');writeout(do.call(rbind,res$curves),'curve_data');writeout(do.call(rbind,res$audit),'fit_audit');saveRDS(rows,file.path(out,'model_row_ids.rds'));saveRDS(bases,file.path(out,'basis_transformations.rds'));write_json(bases,file.path(out,'basis_transformations.json'),pretty=TRUE,digits=17,auto_unbox=TRUE);cat('MODEL PASS COMPLETE\n')
