suppressPackageStartupMessages({library(survey);library(jsonlite)})
out<-'analysis/tasks/V3-I01/rev-1/work';options(survey.lonely.psu='fail');a<-readRDS(file.path(out,'prepared.rds'));list2env(a,.GlobalEnv);writeout<-function(x,n)write.csv(x,file.path(out,paste0(n,'.csv')),row.names=FALSE)
full<-svydesign(ids=~SDMVPSU,strata=~SDMVSTRA,weights=~weight_mec_18yr,nest=TRUE,data=base[is.finite(base$weight_mec_18yr)&base$weight_mec_18yr>0,]);ref<-subset(full,reference)
vars<-c('age','sex','race','cycle_adjust',setdiff(m2,c('age','sex','race','cycle_adjust')),'FI_route',markers)
manifest<-expand.grid(table=c('Table1',paste0('S',2:5)),variable=vars,stringsAsFactors=FALSE);writeout(manifest,'descriptive_test_row_manifest')
describe<-function(d,table,groupvar){d$variables$group<-d$variables[[groupvar]];rr<-list();tests<-list();for(v in vars){x<-d$variables[[v]];coupled<-(v=='FI_route'&&groupvar=='frail')||paste0('quart_',v)==groupvar;dd<-d[!is.na(x)&!is.na(d$variables$group),];dd$variables$value<-dd$variables[[v]];p<-NA_real_;stat<-param<-method<-warn<-'';reason<-if(coupled)'structurally coupled; descriptive only'else''
if(!coupled&&isTRUE(Sys.getenv('V3_TABLE_TESTS')=='APPROVED')){tr<-tryCatch(withCallingHandlers({stopifnot(length(unique(dd$variables$value))>1,length(unique(dd$variables$group))==length(unique(d$variables$group)),degf(dd)>0);if(is.factor(x))svychisq(~value+group,dd,statistic='F')else svyranktest(value~group,dd,test='wilcoxon')},warning=function(w){warn<<-paste(warn,conditionMessage(w),sep=';');invokeRestart('muffleWarning')}),error=function(e)e);if(inherits(tr,'error'))reason<-conditionMessage(tr)else {p<-tr$p.value;stat<-toJSON(as.list(tr$statistic),auto_unbox=TRUE);param<-toJSON(as.list(tr$parameter),auto_unbox=TRUE);method<-tr$method}}
tests[[v]]<-data.frame(table=table,variable=v,p=p,reason=reason,statistic=stat,parameter=param,method=method,warnings=warn,n=nrow(dd$variables),missing_n=nrow(d$variables)-nrow(dd$variables),design_df=degf(dd),group_n=toJSON(as.list(table(dd$variables$group)),auto_unbox=TRUE),planned_family_n=length(vars))
for(g in c('All',sort(unique(as.character(d$variables$group))))){idx<-if(g=='All')rep(TRUE,nrow(d$variables))else as.character(d$variables$group)==g;z<-d[idx,];val<-z$variables[[v]];nall<-length(val);ok<-!is.na(val);n<-sum(ok);w<-weights(z)[ok];val<-val[ok];if(is.factor(x)){for(l in levels(x)){take<-val==l;rr[[length(rr)+1]]<-data.frame(table=table,group=g,variable=v,level=l,total=nall,observed=n,missing=nall-n,n=sum(take),percent=100*mean(take),weighted_percent=100*sum(w[take])/sum(w),median=NA,q25=NA,q75=NA,weighted_median=NA,weighted_q25=NA,weighted_q75=NA)}}else{q<-quantile(val,c(.25,.5,.75),na.rm=TRUE,type=7);zz<-z[ok,];zz$variables$value<-val;wq<-as.numeric(coef(svyquantile(~value,zz,c(.25,.5,.75),ci=FALSE,na.rm=TRUE)));rr[[length(rr)+1]]<-data.frame(table=table,group=g,variable=v,level='',total=nall,observed=n,missing=nall-n,n=NA,percent=NA,weighted_percent=NA,median=q[2],q25=q[1],q75=q[3],weighted_median=wq[2],weighted_q25=wq[1],weighted_q75=wq[3])}}};tt<-do.call(rbind,tests);tt$p_holm<-p.adjust(tt$p,'holm',n=length(vars));tt$p_BH<-p.adjust(tt$p,'BH',n=length(vars));list(desc=do.call(rbind,rr),tests=tt)}
r<-describe(ref,'Table1','frail');writeout(r$desc,'table1_descriptions');writeout(r$tests,'table1_tests');ss<-lapply(seq_along(markers),function(j)describe(ref,paste0('S',j+1),paste0('quart_',markers[j])));writeout(do.call(rbind,lapply(ss,`[[`,'desc')),'S2_S5_descriptions');writeout(do.call(rbind,lapply(ss,`[[`,'tests')),'S2_S5_tests')
# Selection summaries are descriptive, not a missing-at-random test.
sel<-base[base$SEQN%in%a$base$SEQN&!is.na(base$FI30),];selection<-list();for(g in c('sex','race','cycle','age_group'))for(l in unique(as.character(base[[g]][base$RIDAGEYR>=50]))){i<-!is.na(base[[g]])&as.character(base[[g]])==l&base$RIDAGEYR>=50&is.finite(base$weight_mec_18yr)&base$weight_mec_18yr>0;i[is.na(i)]<-FALSE;w<-base$weight_mec_18yr[i];selection[[length(selection)+1]]<-data.frame(variable=g,level=l,n=sum(i),strict_n=sum(!is.na(base$FI_candidate36[i])),route_n=sum(!is.na(base$FI_route[i])),strict_weighted_retention=sum(w*!is.na(base$FI_candidate36[i]))/sum(w),route_weighted_retention=sum(w*!is.na(base$FI_route[i]))/sum(w))};writeout(do.call(rbind,selection),'selection_retention')
flow<-read.csv(file.path(out,'flow_counts.csv'));png(file.path(out,'Figure1_flow.png'),1500,1100,res=150);par(mar=c(1,1,3,1));plot.new();plot.window(xlim=c(0,1),ylim=c(0,1));title('Candidate cohort flow (not author-identical)');coords<-data.frame(stage=c('all_age_parent','age50_input','route36','reference','model2','supplement','diet','strict36'),x=c(.5,.5,.5,.5,.5,.25,.75,.16),y=c(.92,.80,.65,.51,.37,.20,.20,.65));for(j in seq_len(nrow(coords))){cx<-coords$x[j];cy<-coords$y[j];n<-flow$n[match(coords$stage[j],flow$stage)];rect(cx-.16,cy-.035,cx+.16,cy+.035,col='#E5F0F6',border='#204864');text(cx,cy,paste(coords$stage[j],format(n,big.mark=','),sep=': '),cex=.85)};for(j in 1:4)arrows(.5,coords$y[j]-.04,.5,coords$y[j+1]+.04,length=.06);arrows(.5,.33,.25,.24,length=.06);arrows(.5,.33,.75,.24,length=.06);arrows(.34,.78,.16,.69,length=.06);text(.16,.58,'Original strict sensitivity',cex=.8);text(.75,.11,'Separate WTDR2D/7 parent',cex=.8);dev.off()
if(file.exists(file.path(out,'curve_data.csv'))){cc<-read.csv(file.path(out,'curve_data.csv'));for(model in unique(cc$model)){png(file.path(out,if(model=='M2')'Figure2_Model2_curves.png'else'FigS1_plus16_curves.png'),1600,1200,res=160);par(mfrow=c(2,2),mar=c(5,4,3,1));for(m in markers){z<-cc[cc$model==model&cc$marker==m,];if(!nrow(z)){plot.new();title(paste(m,'non-estimable'));next};plot(z$value,z$OR,type='n',log='x',ylim=range(z$low,z$high,1),xlab=paste(m,'(log scale)'),ylab='Conditional OR vs median',main=paste(model,m));polygon(c(z$value,rev(z$value)),c(z$low,rev(z$high)),col='#D5E7F1',border=NA);lines(z$value,z$OR,col='#184C70',lwd=2);abline(h=1,lty=2)};dev.off()}}
if(file.exists(file.path(out,'subgroup_slopes.csv'))){z<-read.csv(file.path(out,'subgroup_slopes.csv'));png(file.path(out,'Figure3_subgroup_forest.png'),2000,1900,res=170);par(mfrow=c(2,2),mar=c(4,10,3,1));for(m in markers){r<-z[z$marker==m,];yy<-rev(seq_len(nrow(r)));ok<-is.finite(r$low)&is.finite(r$high);plot(r$OR,yy,xlim=range(c(r$low[ok],r$high[ok],1)),log='x',yaxt='n',ylab='',xlab='OR per e-fold marker increase',main=m,pch=19);axis(2,at=yy,labels=paste(r$moderator,r$level,sep=': '),las=1,cex.axis=.7);segments(r$low,yy,r$high,yy);abline(v=1,lty=2)};dev.off()}
writeLines(c('Primary: route-confirmed complete36 analyst candidate. Main Model2 MEC-weighted with reliable day1 energy is exploratory energy-adjusted association.', 'Tables use variable-specific observed denominators; survey weighted quantiles are CDF quantiles, unweighted type7 quantiles. Tests, when approved, use variable-specific survey domains.', 'Supplement adds 16 fixed disease/laboratory covariates, overlapping FI outcome components. No causal interpretation.', 'Figure2/FigS1 use fixed3df natural splines, observed boundaries, median reference, pointwise design-t 95% intervals; not recovered author RCS.', 'Figure3 uses pooled models and design Wald interaction F. Subgroup CI are pointwise descriptive.', 'Ordinary beta branch not applicable because FI endpoints exist; no endpoint removal or squeezing. Existing original36 fractional analyses retained externally; new fractional fitting not required.', 'All inferential families separate; full planned denominators used; Holm primary/BH secondary. Reference quartiles/medians fixed before Model2 selection.'),file.path(out,'interpretation_notes.txt'))
cat('DESCRIPTIONS AND FIGURES COMPLETE\n')
